### ISSUE TITLE
目前网站阅读网址改了

### ISSUE THREAD

**Issue by HaaiSo** [qinlili23333/HyReadDownloader#1]
现在官网阅读界面网址是 https://service.ebook.hyread.com.tw/ebookservice/epubreader/hyread/v3/openbook2.jsp
无法显示下载按钮

**Comment by qinlili23333** [comment]
新页面是epub，原理不同了，需要一段时间研究下

**Comment by qinlili23333** [comment]
拿下！
https://greasyfork.org/zh-CN/scripts/449872

**Comment by qinlili23333** [comment]
标题读取暂不支持，自己下载下来后改文件名吧
