### ISSUE TITLE
请问台湾站的jpg可以下载吗？

### ISSUE THREAD

**Issue by HaaiSo** [qinlili23333/HyReadDownloader#2]
[tw.js](https://github.com/qinlili23333/HyReadDownloader/blob/main/tw.js) 这个文件似乎是用来下载jpg的，不过新版网页用不了

新版网址为'https://service.ebook.hyread.com.tw/ebookservice/epubreader/hyread/v3/openbook2.jsp'

**Comment by qinlili23333** [comment]
用twepub.user.js，不过仅支持epub
